name: VENTURA LLC
favicon: null
layout_spectrum: 0.631845775526017
typography_spectrum: 0.15536585659720004
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.4046079695690423
  lightness: 0.017716573551297188
  saturation: 0.520956757478416
  rhythmicContrast: 0.7390916058793664
purpose: []
